#!/usr/bin/env bash
#
# Generate the secrets nobody hands you, and name the ones somebody must.
#
# Half of a production .env is values you invent — an application key, a shared
# token between two of your own services, database passwords. The other half
# comes from a third party. Confusing the two is how a deployment goes live
# with `local-paymob-hmac-secret` still in it, which does not fail: signatures
# simply never verify and every settlement is silently rejected.
#
# So this writes the first half and refuses to finish quietly about the second.
#
# Usage:
#   ./generate-secrets.sh production > /var/www/kaabosh-production/shared/.env
#   ./generate-secrets.sh production --check /path/to/existing/.env
set -Eeuo pipefail

ENVIRONMENT="${1:-production}"
MODE="${2:-generate}"

ROOT_DOMAIN="${KAABOSH_ROOT_DOMAIN:-kaabosh.tech}"

# Values that must come from somewhere else. Listed here so the check below is
# a fact about this file rather than a habit someone has to remember.
REQUIRED_EXTERNAL=(
  PAYMOB_API_KEY
  PAYMOB_INTEGRATION_ID
  PAYMOB_IFRAME_ID
  PAYMOB_HMAC_SECRET
  FAWRY_MERCHANT_CODE
  FAWRY_SECURITY_KEY
  BEON_API_KEY
  BEON_WEBHOOK_SECRET
  SENTRY_LARAVEL_DSN
  AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY
  AWS_BUCKET
)

# Placeholder values that are fine locally and catastrophic in production,
# because none of them fails loudly — they just make verification fail.
PLACEHOLDERS='local-|changeme|your-|example\.com|CHANGE_ME'

secret() { openssl rand -hex 32; }
short()  { openssl rand -hex 12; }

# --------------------------------------------------------------- check mode

if [ "$MODE" = "--check" ]; then
  ENV_FILE="${3:?usage: generate-secrets.sh <environment> --check <path to .env>}"
  [ -r "$ENV_FILE" ] || { echo "Cannot read ${ENV_FILE}" >&2; exit 2; }

  problems=0

  for key in "${REQUIRED_EXTERNAL[@]}"; do
    value="$(grep -E "^${key}=" "$ENV_FILE" | head -1 | cut -d= -f2- || true)"

    if [ -z "$value" ]; then
      echo "MISSING  ${key} — has to come from the provider" >&2
      problems=$((problems + 1))
    elif echo "$value" | grep -qiE "$PLACEHOLDERS"; then
      echo "PLACEHOLDER ${key}=${value} — this will not fail, it will just never verify" >&2
      problems=$((problems + 1))
    fi
  done

  # An APP_KEY that is empty or still the example one makes every encrypted
  # column and every session unreadable the moment it is replaced.
  app_key="$(grep -E '^APP_KEY=' "$ENV_FILE" | head -1 | cut -d= -f2- || true)"
  if [ -z "$app_key" ] || [ "$app_key" = "base64:" ]; then
    echo "MISSING  APP_KEY — generate one before first boot, never after" >&2
    problems=$((problems + 1))
  fi

  if grep -qE '^APP_DEBUG=true' "$ENV_FILE"; then
    echo "UNSAFE   APP_DEBUG=true — stack traces with credentials in them, on a public URL" >&2
    problems=$((problems + 1))
  fi

  if [ "$problems" -gt 0 ]; then
    echo >&2
    echo "${problems} problem(s). Deploying with these is not a smaller problem than not deploying." >&2
    exit 1
  fi

  echo "All generated and external values are present and none is a placeholder." >&2
  exit 0
fi

# ------------------------------------------------------------ generate mode

cat <<ENV
# Generated by deploy/generate-secrets.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
#
# Everything above the second divider was generated here and is final: the
# APP_KEY in particular must never be regenerated once the application has
# written an encrypted value, or those values become unreadable.
#
# Everything below it is blank on purpose. Fill it from the provider, then run
#   deploy/generate-secrets.sh ${ENVIRONMENT} --check <this file>
# which fails if anything is still empty or still a placeholder.

APP_NAME=Kaabosh
APP_ENV=${ENVIRONMENT}
APP_KEY=base64:$(openssl rand -base64 32)
APP_DEBUG=false
APP_URL=https://api.${ROOT_DOMAIN}

LOG_CHANNEL=stack
LOG_LEVEL=warning

# --- platform -------------------------------------------------------------

KAABOSH_ROOT_DOMAIN=${ROOT_DOMAIN}

# Caddy presents this to the on-demand TLS ask endpoint. Without it any
# hostname pointed at this server could have us request a certificate for it.
KAABOSH_TLS_ASK_TOKEN=$(secret)

# Proves to the API that a call came from our own storefront server rather
# than from a browser whose headers a proxy forwarded.
KAABOSH_INTERNAL_TOKEN=$(secret)

# Whose X-Forwarded-* headers are believed. Caddy is on the same box.
TRUSTED_PROXIES=127.0.0.1,::1

KAABOSH_COMMISSION_BASIS_POINTS=100
KAABOSH_SETTLEMENT_CURRENCY=EGP

# --- database -------------------------------------------------------------
# Two roles on purpose: the owner runs migrations and can bypass row-level
# security, the app role can do neither. Provisioning creates both with these.

DB_CONNECTION=pgsql
DB_HOST=127.0.0.1
DB_PORT=5432
DB_DATABASE=kaabosh
DB_USERNAME=kaabosh_app
DB_PASSWORD=$(secret)
DB_OWNER_USERNAME=kaabosh_owner
DB_OWNER_PASSWORD=$(secret)

# --- cache, queue, realtime ------------------------------------------------

REDIS_CLIENT=phpredis
REDIS_HOST=127.0.0.1
REDIS_PORT=6379
CACHE_STORE=redis
QUEUE_CONNECTION=redis
SESSION_DRIVER=redis
SESSION_DOMAIN=.${ROOT_DOMAIN}

BROADCAST_CONNECTION=reverb
REVERB_APP_ID=$(short)
REVERB_APP_KEY=$(short)
REVERB_APP_SECRET=$(secret)
REVERB_HOST=ws.${ROOT_DOMAIN}
REVERB_PORT=443
REVERB_SCHEME=https

# --- first-party origins ---------------------------------------------------
# These are the CORS allow-list and Sanctum's stateful domains. A browser
# refuses a credentialed request from anywhere not named here.

FRONTEND_DASHBOARD_URL=https://app.${ROOT_DOMAIN}
FRONTEND_ADMIN_URL=https://admin.${ROOT_DOMAIN}
FRONTEND_STOREFRONT_URL=https://${ROOT_DOMAIN}
CORS_EXTRA_ORIGINS=
SANCTUM_STATEFUL_DOMAINS=app.${ROOT_DOMAIN},admin.${ROOT_DOMAIN}

# --- payment rails ---------------------------------------------------------
# Left on the fake gateway deliberately. The deploy, the certificate, the
# backups and everything else can be proven before a single merchant account
# exists; switch these to paymob/fawry when the credentials below are real.

KAABOSH_CARD_GATEWAY=fake
KAABOSH_WALLET_GATEWAY=fake
KAABOSH_REFERENCE_GATEWAY=fake
KAABOSH_COD_GATEWAY=fake
KAABOSH_REFERENCE_EXPIRY_HOURS=72

# ===========================================================================
# Everything below comes from a third party. Blank on purpose.
# ===========================================================================

PAYMOB_BASE_URL=https://accept.paymob.com
PAYMOB_API_KEY=
PAYMOB_INTEGRATION_ID=
PAYMOB_IFRAME_ID=
PAYMOB_HMAC_SECRET=

FAWRY_BASE_URL=https://atfawry.fawrystaging.com
FAWRY_MERCHANT_CODE=
FAWRY_SECURITY_KEY=

BEON_BASE_URL=https://api.beon.chat
BEON_API_KEY=
BEON_WEBHOOK_SECRET=

SENTRY_LARAVEL_DSN=
SENTRY_TRACES_SAMPLE_RATE=0.1
SENTRY_SEND_DEFAULT_PII=false

# Object storage for media and for the WAL archive. Cloudflare R2 or
# Backblaze B2 both speak S3; set AWS_ENDPOINT for either.
FILESYSTEM_DISK=s3
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=auto
AWS_BUCKET=
AWS_ENDPOINT=
AWS_USE_PATH_STYLE_ENDPOINT=true
ENV
